volumes:
  pcg-server-volume: {}

secrets:
  db_username:
    file: db_uname.txt
  db_password:
    file: db_password.txt
  db_db:
    file: db.txt

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER_FILE: /run/secrets/db_username
      POSTGRES_DB_FILE: /run/secrets/db_db
      PGUSER: postgres # to prevent healthchecks via "root" user
    secrets:
      - db_password
      - db_username
      - db_db
    volumes:
      - pcg-server-volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 3
  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9000:9000"
    

  